title: <p align="center"> Ankita Maheshwari </p>
logo: /assets/img/IMG-5350.jpg

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/ankita-maheshwari-718790112/">LinkedIn</a> |
  <a href="https://github.com/Ankdemo">GitHub</a>
  
  <br>   
  I'm working on Data Science, Big Data, Spark, Data Engineering related problems.
  I am having experience in both on-premises and cloud data.
  <br>
  </p>

theme: jekyll-theme-minimal
